BEGIN;

SET CLIENT_ENCODING TO 'UTF-8';

DROP TABLE IF EXISTS "user", "contact", "campaign", "campaign_has_contact", "contact_unsubscribed";

CREATE TABLE "user" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" VARCHAR(80) UNIQUE NOT NULL,
    "lastname" VARCHAR(80) NOT NULL,
    "firstname" VARCHAR(80) NOT NULL,
    "password" VARCHAR(80) NOT NULL,
    "createdDate" TIMESTAMP
);

CREATE TABLE "contact" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "civility" VARCHAR(5) NOT NULL,
    "lastname" VARCHAR(80) NOT NULL,
    "firstname" VARCHAR(80) NOT NULL,
    "business" VARCHAR(80),
    "email" VARCHAR(100) NOT NULL,
    "unsubscribedDate" TIMESTAMP,
    "createdDate" TIMESTAMP,
    "contactToken" VARCHAR(134)
);

CREATE TABLE "campaign" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nameCampaign" VARCHAR(80) NOT NULL,
    "subjectCampaign" VARCHAR(80) NOT NULL,
    "linkCampaign" VARCHAR(100),
    "startCampaign" TIMESTAMPTZ NOT NULL,
    "endCampaign" TIMESTAMPTZ NOT NULL,
    "creatorEmail" VARCHAR(80) NOT NULL,
    "nbrContact" INTEGER NOT NULL,
    "mailing" BOOLEAN,
    "full" BOOLEAN,
    "sent" BOOLEAN,
    "textCampaign" VARCHAR(2500),
    "createdDate" TIMESTAMP,
    "campaignToken" VARCHAR(134)
);

CREATE TABLE "campaign_has_contact" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "idCampaign" INTEGER NOT NULL,
    "emailContact" VARCHAR(80) NOT NULL,
    "idList" INTEGER NOT NULL,
    "nameFile" VARCHAR(80),
    "sent" BOOLEAN NOT NULL,
    "openEmail" INTEGER NOT NULL,
    "unsubscribed" BOOLEAN NOT NULL
);

CREATE TABLE "contact_unsubscribed" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "idCampaign" INTEGER NOT NULL,
    "idCampaignUnsubscribed" INTEGER NOT NULL,
    "emailContact" VARCHAR(80) NOT NULL,
    "nameFile" VARCHAR(80),
    "unsubscribed" BOOLEAN NOT NULL
);

COMMIT;


